public class BasicsCalcuation {
    
    //public Integer salary{get;set;}
    public decimal salary{get;set;}
    
    public BasicsCalcuation(){
        salary = 10000;
    }
    
    
    public void addation(){
  
         //static decimal incentive;
        //incentive = salary + 5000;
        //System.debug('the total amount is' +incentive);
        
        /*
        Integer baseSalary = 20000;
        salary  = salary+baseSalary;
        System.debug(salary);
*/
    }
}