public class MethodPractice {

    public static void methods(){
        //System.debug(System.today().addDays(-7));
        //System.debug(System.today().addMonths(7));
        //System.debug(System.today().addYears(7));
        //System.debug(System.today().day());
        //System.debug(System.today().dayOfYear());
        //System.debug(System.today().daysBetween(System.today().addDays(10)));
        //System.debug(date.daysInMonth(2023,3));
        //System.debug(System.today().format());
        //System.debug(Date.isLeapYear(2025));
        //System.debug(System.today().isSameDay(Date.today()));
        //System.debug(System.today().month());
        //System.debug(System.now());
        //Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        //System.debug(gd.get('Contact'));
        //Schema.DescribeSObjectResult[] descResult = Schema.describeSObjects(new String[]{'Account','Contact'});
        //System.debug(Schema.describeSObjects(new List<String>{'Account,Contact'}));
        System.debug(System.Url.getOrgDomainUrl());
    }
}